# Generated by Django 5.0.3 on 2024-05-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikal',
            options={'verbose_name_plural': '2. Artikel'},
        ),
        migrations.AlterModelOptions(
            name='katagori',
            options={'verbose_name_plural': '1. katagori'},
        ),
    ]
