# Generated by Django 5.0.3 on 2024-05-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_alter_artikal_options_alter_katagori_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikal',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Artikel'),
        ),
    ]
