# Generated by Django 5.0.3 on 2024-06-20 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_alter_artikal_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikal',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
