# Generated by Django 5.0.3 on 2024-06-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_artikal_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikal',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
